export const products = [
  {
    id: 1,
    name: "Tijolo",
    image: "http://localhost/images/download1.jpg",
    description: "Tijolo de 8 furos",
  },
  {
    id: 2,
    name: "Cimento",
    image: "http://localhost/images/cimento.jpeg",
    description: "Cimento 42 kilos",
  },
  {
    id: 3,
    name: "Areia",
    image: "http://localhost/images/areia.jpeg",
    description: "Areia 4m³",
  },
  {
    id: 4,
    name: "Seixo",
    image: "http://localhost/images/seixo.jpeg",
    description: "Seixo 4m³",
  },
  {
    id: 5,
    name: "Ferro 3/8",
    image: "http://localhost/images/vergalhao3_8.jpeg",
    description: "Vergalhão 3/8",
  },
  {
    id: 6,
    name: "Tijolo",
    image: "http://localhost/images/download1.jpg",
    description: "Tijolo de 8 furos",
  },
  {
    id: 7,
    name: "Cimento",
    image: "http://localhost/images/cimento.jpeg",
    description: "Cimento 42 kilos",
  },
  {
    id: 8,
    name: "Areia",
    image: "http://localhost/images/areia.jpeg",
    description: "Areia 4m³",
  },
  {
    id: 9,
    name: "Seixo",
    image: "http://localhost/images/seixo.jpeg",
    description: "Seixo 4m³",
  },
  {
    id: 10,
    name: "Ferro 3/8",
    image: "http://localhost/images/vergalhao3_8.jpeg",
    description: "Vergalhão 3/8",
  },
  {
    id: 11,
    name: "Tijolo",
    image: "http://localhost/images/download1.jpg",
    description: "Tijolo de 8 furos",
  },
  {
    id: 12,
    name: "Cimento",
    image: "http://localhost/images/cimento.jpeg",
    description: "Cimento 42 kilos",
  },
  {
    id: 13,
    name: "Areia",
    image: "http://localhost/images/areia.jpeg",
    description: "Areia 4m³",
  },
  {
    id: 14,
    name: "Seixo",
    image: "http://localhost/images/seixo.jpeg",
    description: "Seixo 4m³",
  },
  {
    id: 15,
    name: "Ferro 3/8",
    image: "http://localhost/images/vergalhao3_8.jpeg",
    description: "Vergalhão 3/8",
  },
];
